### ISSUE TITLE
question about python setup.py install

### ISSUE THREAD

**Issue by zhqia** [shnhrtkyk/FWNet2#1]
got error like this:
ext_src/src/group_points.cpp : 28 : 3 : error: expected 'while' before 'at'
  28|  at::Tensor output=
      |  ^~
ext_src/src/group_points.cpp : 28 : 3 : error: expected '(' before 'at'
  28|  at::Tensor output=
      |  ^~
      |  (
ext_src/src/group_points.cpp : 28 : 14 : error: expected primary-expression before 'output'
  28|  at::Tensor output=
      |                  ^~~~~
ext_src/src/group_points.cpp : 28 : 13 : error: expected ')' before 'output'
  28|  at::Tensor output=
      |  ~~           ^~~~~
      |                  )
ext_src/src/group_points.cpp : 28 : 13 : error: expected ':' before 'output'
  28|  at::Tensor output=
      |                  ^~~~~
      |                  :
ext_src/src/group_points.cpp : 28 : 14 : error:  'output' was not declared in this scope; did you mean 'c10::attr::output'?
  28|  at::Tensor output=
      |                  ^~~~~
      |                  c10::attr::output

**Comment by shnhrtkyk** [comment]
I have followed the VoteNet code.
Please refer to this: https://github.com/facebookresearch/votenet
We use cuda10.1 and cudnn7.6.
