### ISSUE TITLE
questions about model

### ISSUE THREAD

**Issue by zhqia** [shnhrtkyk/FWNet2#2]
there is only one model imported to train.py. So what is model1 to model6?

**Comment by shnhrtkyk** [comment]
model1 to model6 are remnants of experiments in which we changed the number of points to be grouped, the radius of the ball query, and the number of layers.
These have been modified to read the model in the repository.

**Comment by zhqia** [comment]
> model1 to model6 are remnants of experiments in which we changed the number of points to be grouped, the radius of the ball query, and the number of layers. These have been modified to read the model in the repository.

I have learnt that. Thank you for your answer.
