### ISSUE TITLE
questions about testing

### ISSUE THREAD

**Issue by zhqia** [shnhrtkyk/FWNet2#3]
I wonder if infer.py is used for testing, if I understand correctly. So is the data used by testing also preprocessed as a fixed size patch like training process? Do they use the same preprocessing file? Or the testing process require projection? Is it necessary to map the prediction result of sampling points to projection points in infer.py?
And about the article, how can I realize the five-fold cross-validation? Should I divide the training data into five groups, and use four of them in training and one of them for validation, and repeat it five times in train.py to generate the final model, and then use the testing data to test the result?

**Comment by shnhrtkyk** [comment]
- infer.py  
That's right.
You can use infer.py to test with a pre-trained model.
In infer.py, no preprocessing is needed because the inference is done while cutting to a fixed point.

- cross valid
When I did the cross-validation, I divided the stats.csv into 5 parts.

**Comment by zhqia** [comment]
> 

Thanks for your answer. I wonder whether you use one part of stats.csv to validation or testing when you did cross-validation

**Comment by shnhrtkyk** [comment]
![trainvaltest](https://user-images.githubusercontent.com/49538481/147798513-cb2b0bec-b9a6-4877-99db-a564eefa5502.png)
- test 
The full waveform data used in the experiment is the black box, and the test was cut out first as shown in red.
(To avoid being included in the training data)
- cross-val
During training, create a patch with tes and non-data (blue), and randomly divide the stats.csv into 5 parts.

**Comment by zhqia** [comment]
> 

I have learnt that. Thank you for your answer.
